import { Point, Quiz } from "../types";

interface Category {
  id: number;
  name: string;
  point: Point;
}

export const categories: Category[] = [
  { id: 1, point: 10, name: "Psaumes" },
  { id: 2, point: 10, name: "Pour faire plaisir à Léa et Mathilde" },
  { id: 3, point: 10, name: "En tapant des mains" },
  { id: 4, point: 10, name: "Écritures" },
  { id: 5, point: 10, name: "Exo" },
  { id: 6, point: 10, name: "Getty" },
  { id: 7, point: 20, name: "On ne les présente plus" },
  { id: 8, point: 20, name: "O Jésus mon Sauveur" },
  { id: 9, point: 20, name: "Vous pouvez répéter la question ?" },
  { id: 10, point: 20, name: "Miroir miroir" },
  { id: 11, point: 20, name: "En canon" },
  { id: 12, point: 20, name: "Avec des répétitions" },
  { id: 13, point: 30, name: "Avec le mot « exalté »" },
  { id: 14, point: 30, name: "Voyage voyage" },
  { id: 15, point: 30, name: "Chants de Noël" },
  { id: 16, point: 30, name: "Made in Gerland" },
  { id: 17, point: 30, name: "Aux armes !" },
  { id: 18, point: 30, name: "Attributs du Père" },
  { id: 19, point: 40, name: "Pour Pâques" },
  { id: 20, point: 40, name: "Getty" },
  { id: 21, point: 40, name: "Station balnéaire" },
  { id: 22, point: 40, name: "Psaumes" },
  { id: 23, point: 40, name: "On ne les présente plus (re-traduit à Gerland)" },
  { id: 24, point: 40, name: "Eschatologie" },
  { id: 25, point: 50, name: "Onomatopée ou interjection" },
  { id: 26, point: 50, name: "Écritures" },
  { id: 27, point: 50, name: "Sur du classique" },
  { id: 28, point: 50, name: "Christologie" },
  { id: 29, point: 50, name: "Proverbes 1.7" },
  { id: 30, point: 50, name: "Pour se repentir" },
];

export const quizzes: Quiz[] = [
  { id: 1, categoryId: 1, title: "Psaume 1" },
  { id: 2, categoryId: 1, title: "Psaume 47" },
  { id: 3, categoryId: 2, title: "C’est ton roi qui t’appelle" },
  { id: 4, categoryId: 2, title: "Chantons !" },
  { id: 5, categoryId: 3, title: "Grandes et merveilleuses" },
  { id: 6, categoryId: 3, title: "Venez le célébrer" },
  { id: 7, categoryId: 4, title: "Héritiers" },
  { id: 8, categoryId: 4, title: "Ta Parole" },
  { id: 9, categoryId: 5, title: "Règne en moi" },
  { id: 10, categoryId: 5, title: "Digne es-tu" },
  { id: 11, categoryId: 6, title: "Tiens toi debout Église du grand Roi" },
  { id: 12, categoryId: 6, title: "C’est par la foi" },
  { id: 13, categoryId: 7, title: "À toi la gloire" },
  { id: 14, categoryId: 7, title: "Quel ami fidèle et tendre" },
  { id: 15, categoryId: 8, title: "Sauveur du monde" },
  { id: 16, categoryId: 8, title: "O mystère infini" },
  { id: 17, categoryId: 9, title: "Qui donc dans le ciel" },
  { id: 18, categoryId: 9, title: "Qui est Dieu comme toi ?" },
  { id: 19, categoryId: 10, title: "Oh Viens Jésus (Noël)" },
  { id: 20, categoryId: 10, title: "Oh viens Jésus (Écritures)" },
  { id: 21, categoryId: 11, title: "Mon seul abri" },
  { id: 22, categoryId: 11, title: "quand j’invoque le Seigneur" },
  { id: 23, categoryId: 12, title: "Gloire, gloire, gloire" },
  { id: 24, categoryId: 12, title: "Saint, saint, saint !" },
  { id: 25, categoryId: 13, title: "Il est exalte" },
  { id: 26, categoryId: 13, title: "Exalte avec moi" },
  { id: 27, categoryId: 14, title: "Quand les montagnes" },
  { id: 28, categoryId: 14, title: "Les anges dans nos campagnes" },
  { id: 29, categoryId: 15, title: "Voici Noël" },
  { id: 30, categoryId: 15, title: "Peuple Fidèle" },
  { id: 31, categoryId: 16, title: "Environné d’un éclat." },
  { id: 32, categoryId: 16, title: "Ta grâce au Dieu" },
  { id: 33, categoryId: 17, title: "Avant les trônes" },
  { id: 34, categoryId: 17, title: "Bénis soit le nom" },
  { id: 35, categoryId: 18, title: "Dieu créateur" },
  { id: 36, categoryId: 18, title: "Dieu tout puissant" },
  { id: 37, categoryId: 19, title: "Alléluia Jésus vit" },
  { id: 38, categoryId: 19, title: "C’est aujourd’hui la victoire" },
  { id: 39, categoryId: 20, title: "O l’ampleur de la tâche" },
  { id: 40, categoryId: 20, title: "Viens peuple du Seigneur vivant" },
  { id: 41, categoryId: 21, title: "Comme un phare" },
  { id: 42, categoryId: 21, title: "Mon ancre et ma voile" },
  { id: 43, categoryId: 22, title: "Psaume 42" },
  { id: 44, categoryId: 22, title: "Psaume 92" },
  { id: 45, categoryId: 23, title: "Avant les trônes" },
  { id: 46, categoryId: 23, title: "Bénis soit le nom" },
  { id: 47, categoryId: 24, title: "A la fin des temps" },
  { id: 48, categoryId: 24, title: "Il est un jour" },
  { id: 49, categoryId: 25, title: "Ô merveilleuse histoire" },
  { id: 50, categoryId: 25, title: "Ô Jésus mon Roi mon Maitre" },
  { id: 51, categoryId: 26, title: "Notre Dieu" },
  { id: 52, categoryId: 26, title: "Dieu sublime" },
  { id: 53, categoryId: 27, title: "Les cieux et la terre" },
  { id: 54, categoryId: 27, title: "Entonnons un saint cantique" },
  { id: 55, categoryId: 28, title: "Mon espérance est en Jésus" },
  { id: 56, categoryId: 28, title: "Jésus est mon divin berger" },
  { id: 57, categoryId: 29, title: "Craignons l’Éternel" },
  { id: 58, categoryId: 29, title: "Psaume 6" },
  { id: 59, categoryId: 30, title: "Seigneur tu vois mon coeur" },
  { id: 60, categoryId: 30, title: "Pardon, Seigneur pardon" },
];
